# Generated by Django 2.2 on 2020-01-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_applied',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
